### ISSUE TITLE
suave-geth locally does not revert when a confidential request update state storage

### ISSUE THREAD

**Issue by haythemsellami** [flashbots/suave-geth#243]
### What version of Suave are you on?

suave-geth version 0.1.5-23d7a718-20240404

### Operating System

macOS (Apple Silicon)

### Describe the bug

I'm building something on top of Suave, and was following the documentation on how to make an off-chain call to ChatGPT.

In the example https://suave-alpha.flashbots.net/concepts/offchain-http, a new instance of `ChatGPT` is created inside of the `offchain()` and it updates the storage state of that contract `apiKey = _apiKey;`.

When running that example locally using `suave-geth`, and calling the `offchain()` method, it does not revert.
When deploying the same contract on Rigil testnet, it does revert with `panic: confidential request cannot modify state storage`. I'm assuming this is a bug as the behaviour locally should mimic the one in production?

**Comment by haythemsellami** [comment]
How to reproduce:

- https://github.com/eaglelabs-consulting/playground/blob/main/src/ChatGPTBug.sol & https://github.com/eaglelabs-consulting/playground/blob/main/app/deploy_chatgptbug.go.
- Fill in `.env` file from `.env.example`

```sh
$ source .env
$ forge build && go run app/deploy_chatgptbug.go
```

**Comment by haythemsellami** [comment]
Is this valid, or I'm missing something?

**Comment by ferranbt** [comment]
Hey, sorry for the delay. This is the expected behaviour, when you tried it the Rigil nodes were not updated to the latest version that included [this PR](https://github.com/flashbots/suave-geth/commit/cc42af4c3090da77516ba56ba1fb530ca22c51e3) which was introduced to make the uses cases like the ChatGPT example possible.
