### ISSUE TITLE
`runtime error: invalid memory address or nil pointer dereference` 

### ISSUE THREAD

**Issue by arcticfloyd1984** [flashbots/suave-geth#256]
### What version of Suave are you on?

suave-geth version 0.1.5-23d7a718-20240404

### What command(s) is the bug in?

suave-geth spell conf-request <contract-address> 'offchain()'

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am following [this](https://suave-alpha.flashbots.net/tutorials/deploy-contracts) tutorial and deploying my first Suapp. I am getting the following error:

![Screenshot 2024-06-19 at 1 20 01 PM](https://github.com/flashbots/suave-geth/assets/23353399/20c603db-f60d-4ddc-a5b8-d97d95edf5d1)

The logs in the sauve-geth console are:
![Screenshot 2024-06-19 at 1 21 21 PM](https://github.com/flashbots/suave-geth/assets/23353399/9e7e9928-a489-49d8-8e84-8e64c4a62bfe)

**Comment by ferranbt** [comment]
Hey, can you share the artifacts folder generated? it seems that it is missing the ABI code.

**Comment by ferranbt** [comment]
Hi! Thank you for the artifacts. Found the error, `forge` seems to include a new build-info JSON file in the artifacts folder. This should be fixed with #267 now. We will be doing a new release by the end of the week most likely with the new changes.
